### ISSUE TITLE
runE2Code / runString function

### ISSUE THREAD

**Issue by Vurv78** [Vurv78/VExtensions#27]
A function that lets you run e2 code. That's it. I'm not sure how hard this would be to implement, but it won't be *easy*

**Comment by Cheatoid** [comment]
This would be helpful if you mean to run the code in the context of the running E2, without changing its code.
I have faced kind of a problem today, mostly my own fault because I was using `entity:remoteSetCode`, which produced undesired side effects such as holos that were created by the E2, ended up getting removed as the E2's code was changed. So I stopped using `remoteSetCode` altogether...
Sure enough, I would also think this isn't something easy.
Question is, how do you mean for `@persist` and other stuff to work?
```golo
@outputs Num
@persist Text:string
Num = 123
function func() { print( "Hello from func", Text ) }

runCode( "Text = \"Foo\" \n print( Num, func() )" )
```

**Comment by Vurv78** [comment]
Well that'd just error because func doesn't exist, but I don't think we'd have to do anything in particular as long as we kill the e2 right away so it doesn't actually runOn anything.
